Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -63,7 +63,7 @@ jobs:
         run: |
           SONAR_RESPONSE=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
                           "https://sonarcloud.io/api/measures/component?component=Shara-org_sample-java-repo&metricKeys=code_smells,vulnerabilities,bugs")
-          echo "::set-output name=sonar_response::$SONAR_RESPONSE"
+          #echo "::set-output name=sonar_response::$SONAR_RESPONSE"
       - name: Check Sonar Report
         run: |
           SONAR_RESPONSE="${{ steps.retrieve_metrics.outputs.sonar_response }}"
@@ -73,9 +73,9 @@ jobs:
           echo "CODE_SMELLS: $CODE_SMELLS"
           echo "VULNERABILITIES: $VULNERABILITIES"
           echo "BUGS: $BUGS"
-          if : " $CODE_SMELLS -gt $CODE_SMELLS_THRESHOLD || $VULNERABILITIES -gt $VULNERABILITIES_THRESHOLD || $BUGS -gt $BUGS_THRESHOLD "; then
-            echo "Sonar report does not meet quality standards. Exiting with an error."
-            exit 1
+          if [[ $CODE_SMELLS -gt $CODE_SMELLS_THRESHOLD || $VULNERABILITIES -gt $VULNERABILITIES_THRESHOLD || $BUGS -gt $BUGS_THRESHOLD ]]; then
+          echo "Sonar report does not meet quality standards. Exiting with an error."
+          exit 1
           fi
 
 
